### ISSUE TITLE
Can't build wine32on64 on mac os 15

### ISSUE THREAD

**Issue by clesauln** [GabLeRoux/macos-crossover-cloud-build#26] opened 2021-10-25 21:00 UTC
The step to build wine32on64 does not succeed.
- environment:
-  **crossover-21.0.0**
- version mac-os: **15.7**

wrong pointer : `sources/wine/dlls/bcrypt/macos.c:54:1: error: 
      array size is negative
C_ASSERT( sizeof(struct key_data) <= sizeof(((struct key *)0)->private) );

/macos-crossover-wine-cloud-builder-main/sources/wine/include/winnt.h:394:51: note: 
      expanded from macro 'C_ASSERT'
#define C_ASSERT(e) extern void __C_ASSERT__(int [(e)?1:-1])
`

Tried with version 20.0.0 and can't compile too

**Comment by Gcenx** [comment] 2021-10-25 21:23
Little hard to say what’s wrong as you’ve not provided much output.

**Comment by clesauln** [comment] 2021-10-27 20:53
This the build script, plus i don't know if it even more needed to add missing library llvm/clang if the target is 20.0.0 :

```
#!/usr/bin/env bash

set -ex

echo Wine-Crossover-MacOS

export GITHUB_WORKSPACE=$(pwd)

#if [ -z "$CROSS_OVER_VERSION" ]; then
export CROSS_OVER_VERSION=20.0.2
#fi

# avoid weird linker errors with Xcode 10 and later
export MACOSX_DEPLOYMENT_TARGET=10.14
# crossover source code to be downloaded
export CROSS_OVER_SOURCE_URL=https://media.codeweavers.com/pub/crossover/source/crossover-sources-${CROSS_OVER_VERSION}.tar.gz
export CROSS_OVER_LOCAL_FILE=crossover-${CROSS_OVER_VERSION}
# directories / files inside the downloaded tar file directory structure
export LLVM_MAKEDIR=$GITHUB_WORKSPACE/sources/$([[ ${CROSS_OVER_VERSION} == 2?.* ]] && echo "clang/llvm" || echo "llvm")
export CLANG_MAKEDIR=$GITHUB_WORKSPACE/sources/$([[ ${CROSS_OVER_VERSION} == 2?.* ]] && echo "clang/clang" || echo "clang")
export WINE_CONFIGURE=$GITHUB_WORKSPACE/sources/wine/configure
export DXVK_BUILDSCRIPT=$GITHUB_WORKSPACE/sources/dxvk/package-release.sh
# build directories
export BUILDROOT=$GITHUB_WORKSPACE/build
export LLVM_BUILDDIR=$GITHUB_WORKSPACE/build/llvm
export CLANG_BUILDDIR=$GITHUB_WORKSPACE/build/clang
# target directory for installation
export INSTALLROOT=$GITHUB_WORKSPACE/install
export PACKAGE_UPLOAD=$GITHUB_WORKSPACE/upload
# artifact names
export TOOLS_INSTALLATION=build-tools-cx${CROSS_OVER_VERSION}
export WINE_INSTALLATION=wine-cx${CROSS_OVER_VERSION}
export DXVK_INSTALLATION=dxvk-cx${CROSS_OVER_VERSION}


echo Install Dependencies
# build tools
brew install  cmake            \
              ninja

# build dependencies for wine / crossover
brew install  freetype         \
              bison            \
              krb5             \
              faudio           \
              sdl2             \
              gphoto2          \
              sane-backends    \
              gst-plugins-base \
              mpg123           \
              little-cms2      \
              libpng           \
              mingw-w64        \
              molten-vk

echo Add bison and krb5 to PATH
export PATH="$(brew --prefix bison)/bin":${PATH}
export PATH="$(brew --prefix krb5)/bin":${PATH}

echo Add llvm/clang to PATH for later
export PATH="${INSTALLROOT}/${TOOLS_INSTALLATION}/bin":${PATH}


############ Download and Prepare Source Code ##############

echo Get Source
#curl -o ${CROSS_OVER_LOCAL_FILE}.tar.gz ${CROSS_OVER_SOURCE_URL}

echo Extract Source
tar xf ${CROSS_OVER_LOCAL_FILE}.tar.gz

echo Add missing llvm/clang
#curl -o crossover-20.0.0.tar.gz https://media.codeweavers.com/pub/crossover/source/crossover-sources-20.0.0.tar.gz
tar -xf crossover-20.0.0.tar.gz sources/clang


echo "Patch Add missing distversion.h"
# Patch provided by Josh Dubois, CrossOver product manager, CodeWeavers.
pushd sources/wine
patch -p1 < ${GITHUB_WORKSPACE}/distversion.patch
popd



echo "Patch wcslen() in ntdll/wcstring.c to prevent crash if a nullptr is suppluied to the function (HACK)"
pushd sources/wine
patch -p1 < ${GITHUB_WORKSPACE}/wcstring.patch
popd

echo "Patch msvcrt to export the missing sincos function"
# https://github.com/wine-mirror/wine/commit/f0131276474997b9d4e593bbf8c5616b879d3bd5
pushd sources/wine
patch -p1 < ${GITHUB_WORKSPACE}/msvcrt-sincos.patch
popd

echo Patch DXVK
patch sources/dxvk/src/util/rc/util_rc_ptr.h < dxvk_util_rc_ptr.patch


############ Build LLVM / Clang ##############

echo Configure LLVM
mkdir -p ${LLVM_BUILDDIR}
pushd ${LLVM_BUILDDIR}
cmake -G Ninja \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${INSTALLROOT}/${TOOLS_INSTALLATION}" \
    ${LLVM_MAKEDIR}
popd

echo Build LLVM
pushd ${LLVM_BUILDDIR}
Ninja
popd

echo Install LLVM
pushd ${LLVM_BUILDDIR}
Ninja install
popd

echo Configure Clang
mkdir -p ${CLANG_BUILDDIR}
pushd ${CLANG_BUILDDIR}
cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${INSTALLROOT}/${TOOLS_INSTALLATION}" \
    ${CLANG_MAKEDIR}
popd

echo Build Clang
pushd ${CLANG_BUILDDIR}
Ninja
popd

echo Install Clang
pushd ${CLANG_BUILDDIR}
Ninja install
popd

echo Tar Build Tools
pushd ${INSTALLROOT}
tar -czf ${TOOLS_INSTALLATION}.tar.gz ${TOOLS_INSTALLATION}
popd

echo Upload Build Tools
mkdir -p ${PACKAGE_UPLOAD}
cp ${INSTALLROOT}/${TOOLS_INSTALLATION}.tar.gz ${PACKAGE_UPLOAD}/


############ Build DXVK ##############

#    Echo "Installing dependencies for dxvk"
    brew install  coreutils \
                  meson     \
                  glslang
 #   echo Build DXVK
 #   PATH="$(brew --prefix coreutils)/libexec/gnubin:${PATH}" ${DXVK_BUILDSCRIPT} master ${INSTALLROOT}/${DXVK_INSTALLATION} --no-package
#
 #   echo Tar DXVK
#    pushd ${INSTALLROOT}
#    popd
#
#    echo Upload DXVK
#    mkdir -p ${PACKAGE_UPLOAD}
 #ƒ   cp ${INSTALLROOT}/${DXVK_INSTALLATION}.tar.gz ${PACKAGE_UPLOAD}/
#fi

############ Build 64bit Version ##############

echo Configure wine64
export CC=clang
export CXX=clang++
# see https://github.com/Gcenx/macOS_Wine_builds/issues/17#issuecomment-750346843
export CROSSCFLAGS=$([[ ${CROSS_OVER_VERSION} == 19.* ]] && echo "-g -O2 -fcommon" || echo "-g -O2")
# Xcode12 by default enables '-Werror,-Wimplicit-function-declaration' (49917738)
# this causes wine(64) builds to fail so needs to be disabled.
# https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
export CFLAGS="-g -O2 -Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-format"
export LDFLAGS="-Wl,-headerpad_max_install_names"

export SDL2_CFLAGS="-I$(brew --prefix sdl2)/"$([[ ${CROSS_OVER_VERSION} == 21.* ]] && echo "include/SDL2" || echo "include")
export GPHOTO2_CFLAGS="-I$(brew --prefix libgphoto2)/include -I$(brew --prefix libgphoto2)/include/gphoto2"
export GPHOTO2_PORT_CFLAGS="-I$(brew --prefix libgphoto2)/include -I$(brew --prefix libgphoto2)/include/gphoto2"

export PNG_CFLAGS="-I$(brew --prefix libpng)/include"
export PNG_LIBS="-L$(brew --prefix libpng)/lib"

export LDFLAGS="-L $(brew --prefix molten-vk)/lib ${LDFLAGS}"

mkdir -p ${BUILDROOT}/wine64
pushd ${BUILDROOT}/wine64
${WINE_CONFIGURE} \
        --enable-win64 \
        --disable-tests \
        --without-alsa \
        --without-capi \
        --without-dbus \
        --without-inotify \
        --without-oss \
        --without-pulse \
        --without-udev \
        --without-v4l2 \
        --without-gsm \
        --with-png \
        --with-sdl \
        --with-vulkan \
        --without-x
popd

echo Build wine64
pushd ${BUILDROOT}/wine64
make -j$(sysctl -n hw.ncpu 2>/dev/null)
popd


############ Build 32bit Version (WoW64) ##############
echo "c-------------------------------------------------c"
echo Configure wine32on64
export CC=clang
export CXX=clang++
# see https://github.com/Gcenx/macOS_Wine_builds/issues/17#issuecomment-750346843
export CROSSCFLAGS=$([[ ${CROSS_OVER_VERSION} == 19.* ]] && echo "-g -O2 -fcommon" || echo "-g -O2")
# Xcode12 by default enables '-Werror,-Wimplicit-function-declaration' (49917738)
# this causes wine(64) builds to fail so needs to be disabled.
# https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
export CFLAGS="-g -O2 -Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-format"
export LDFLAGS="-Wl,-headerpad_max_install_names"

export SDL2_CFLAGS="-I$(brew --prefix sdl2)/"$([[ ${CROSS_OVER_VERSION} == 21.* ]] && echo "include/SDL2" || echo "include")
export GPHOTO2_CFLAGS="-I$(brew --prefix libgphoto2)/include -I$(brew --prefix libgphoto2)/include/gphoto2"
export GPHOTO2_PORT_CFLAGS="-I$(brew --prefix libgphoto2)/include -I$(brew --prefix libgphoto2)/include/gphoto2"

export PNG_CFLAGS="-I$(brew --prefix libpng)/include"
export PNG_LIBS="-L$(brew --prefix libpng)/lib"


export DISABLE_VULKAN="--without-vkd3d --without-vulkan --disable-vulkan_1 --disable-winevulkan"


mkdir -p ${BUILDROOT}/wine32on64
pushd ${BUILDROOT}/wine32on64
${WINE_CONFIGURE} \
        --enable-win32on64 \
        --with-wine64=${BUILDROOT}/wine64 \
        --disable-tests \
        --without-alsa \
        --without-capi \
        --without-dbus \
        --without-inotify \
        --without-oss \
        --without-pulse \
        --without-udev \
        --without-v4l2 \
        --disable-winedbg \
        --without-cms \
        --without-gstreamer \
        --without-gsm \
        --without-gphoto \
        --without-sane \
        --with-png \
        --with-sdl \
        --without-krb5 \
        ${DISABLE_VULKAN} \
        --without-x
popd

echo Build wine32on64
pushd ${BUILDROOT}/wine32on64
make -j$(sysctl -n hw.activecpu 2>/dev/null)
popd


############ Install wine ##############

echo Install wine32on64
pushd ${BUILDROOT}/wine32on64
make install-lib DESTDIR="${INSTALLROOT}/${WINE_INSTALLATION}"
popd

echo Install wine64
pushd ${BUILDROOT}/wine64
make install-lib DESTDIR="${INSTALLROOT}/${WINE_INSTALLATION}"
popd


############ Bundle and Upload Deliverable ##############

echo Tar Wine
pushd ${INSTALLROOT}
tar -czvf ${WINE_INSTALLATION}.tar.gz ${WINE_INSTALLATION}
popd

echo Upload Wine
mkdir -p ${PACKAGE_UPLOAD}
cp ${INSTALLROOT}/${WINE_INSTALLATION}.tar.gz ${PACKAGE_UPLOAD}/

```

**Comment by Gcenx** [comment] 2021-10-27 21:03
I was referring to the output from terminal during the build not the build_local.sh contents.

However the script is missing a build dep, `mingw-w64`, installing that should resolve the mentioned issue.

**Comment by Gcenx** [comment] 2021-10-27 21:24
The issue should be resolved with https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/commit/8ded0bcd2524ddc643e6d6998efef83eb7df2ec8

**Comment by clesauln** [comment] 2021-10-27 21:42
i'll try.
Also i have tested with version 20.0.0

and gives me at the step configure wine 64 :
configure: creating ./config.status
config.status: creating Make.tmp
config.status: creating include/config.h
config.status: include/config.h is unchanged
config.status: linking /Users/clement/Library/crossover/sources/wine/tools/winewrapper to wine
config.status: linking /Users/clement/Library/crossover/sources/wine/tools/winewrapper to wine64
config.status: executing include/stamp-h commands
config.status: executing tools/makedep commands
config.status: executing Makefile commands
/Users/clement/Library/crossover/sources/wine/programs/winedbg/resource.h:23: error: distversion.h: No such file or directory
/Users/clement/Library/crossover/sources/wine/programs/winedbg/crashdlg.c:31: note: resource.h was first included here
config.status: error: could not create Makefile

**Comment by Gcenx** [comment] 2021-10-27 21:46
Please grab the latest commit and try again.

**Comment by clesauln** [comment] 2021-10-27 22:15
I have take the patch and go further but It has stopped at build wine64:

the last prompt:

-Wl,--wine-builtin -shared \
  /Users/clement/Library/crossover/sources/wine/dlls/d3dcompiler_34/d3dcompiler_34.spec -mno-cygwin \
  asmparser.cross.o blob.cross.o bytecodewriter.cross.o compiler.cross.o main.cross.o \
  preproc.cross.o reflection.cross.o utils.cross.o asmshader.tab.cross.o hlsl.tab.cross.o \
  ppy.tab.cross.o asmshader.yy.cross.o hlsl.yy.cross.o ppl.yy.cross.o version.res \
  ../../dlls/dxguid/libdxguid.cross.a ../../dlls/uuid/libuuid.cross.a 

and nothing after

**Comment by Gcenx** [comment] 2021-10-27 22:19
You should have git cloned the repository so you have everthing needed.

The last line is no use you need to proved the line(s) that start with `error:` grab a couple before and after.

**Comment by clesauln** [comment] 2021-10-28 21:57
Still the same error : 

  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/dlls/browseui -I include -I \
  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/include -I \
  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/include/msvcrt -D__WINESRC__ \
  -D_UCRT -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value \
  -fno-omit-frame-pointer -gdwarf-2 -gstrict-dwarf -g -O2
/Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/dlls/bcrypt/macos.c:54:1: error: array size is negative
C_ASSERT( sizeof(struct key_data) <= sizeof(((struct key *)0)->private) );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/include/winnt.h:394:51: note: expanded from macro
      'C_ASSERT'
#define C_ASSERT(e) extern void __C_ASSERT__(int [(e)?1:-1])
                                                  ^~~~~~~~
1 error generated.
make: *** [dlls/bcrypt/macos.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by Gcenx** [comment] 2021-10-28 23:51
Would have been nice to see the line that starts with `error:` but I believe the issue is the lack of gnutls as that's another hard requirement.

Most of the testing was with the github actions workflow not the local one, my own system it setup for compiling wine at least every two weeks I already have everything required to compile wine installed.

The new commit will now also install the required `gnutls`

**Comment by clesauln** [comment] 2021-10-29 21:15
The line before : 
 -I dlls/browseui -I \
  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/dlls/browseui -I include -I \
  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/include -I \
  /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/include/msvcrt -D__WINESRC__ \
  -D_UCRT -DWINE_CROSS_PE -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wabsolute-value \
  -fno-omit-frame-pointer -gdwarf-2 -gstrict-dwarf -g -O2
i686-w64-mingw32-gcc -c -o dlls/browseui/aclsource.cross.o /Users/clement/Softs/macos-crossover-wine-cloud-builder/sources/wine/dlls/browseui/**aclsource.c** \

I found similar issue, blocked at 32 bits build [#1456](https://github.com/curl/curl/issues/1456)

The crossover 21 works on my mac. 

this thread could be related : [how-to-get-wine-working-on-catalina](https://apple.stackexchange.com/questions/373851/how-to-get-wine-working-on-catalina)

**Comment by Gcenx** [comment] 2021-10-29 22:15
The provided output doesn’t show any errors.

The things you’ve linked to are not related as you’ve already said CX21.0.0 compiled without issue. The only things been compiled as 32Bit are Windows PE binaries that’s being handled by `i686-w64-mingw32-gcc`

Your trying to build CX20.0.0, don’t bother with that one, build CX20.0.4 that includes fixes the new gcc10 behavior of `-fno-common`

**Comment by clesauln** [comment] 2021-10-31 12:28
You where right
brew install gnutls solved the issue.

I have to test it now - linked to the old thread :
https://githubmemory.com/repo/GabLeRoux/macos-crossover-cloud-build/issues/21

**Comment by Gcenx** [comment] 2021-11-01 02:06
Resolved

**Closed as completed by Gcenx** 2021-11-01 02:06 UTC
